

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ADO_to_Azure_ServiceConnection'
    backendAzureRmResourceGroupName: 'rg-c2s-internal-srikanthk'
    backendAzureRmStorageAccountName: 'srikanth2store'
    backendAzureRmContainerName: 'mystate'
    backendAzureRmKey: 'prod.terraform.tfstate'
  
- task: TerraformTaskV4@4
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV4@4
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'ADO_to_Azure_ServiceConnection'

- task: TerraformTaskV4@4
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'ADO_to_Azure_ServiceConnection'


